name: Notificacion de cambios

on:
  push:
    branches:
      - main

jobs:
  enviar-alerta:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar POST a ntfy.sh
        run: |
          curl -H "Title: Código subido a main por ${{ github.actor }}" \
               -H "Priority: 5" \
               -d "El usuario ${{ github.actor }} ha subido código nuevo al repositorio. Ver commit: https://github.com/${{ github.repository }}/commit/${{ github.sha }}" \
               https://ntfy.sh/devops-itla 